### ISSUE TITLE
Add smooth-scroll

### ISSUE THREAD

**Issue by saurabhranjan1806** [sedg-jss/edc-web#2]

**Comment by anantjain6** [comment]
I faced the same on chrome on windiws but didn't faced it in chrome on ubuntu

**Comment by saurabhranjan1806** [comment]
i am facing it on chrome on ubuntu too, on every browser.
![image](https://user-images.githubusercontent.com/15872681/31057096-8f9ac81e-a6fa-11e7-8f99-468324185f41.png)

**Comment by anantjain6** [comment]
Found the reason
Its because of sticky navigation bar (navbar)

**Comment by saurabhranjan1806** [comment]
nice, can u fix it?

**Comment by geekayush** [comment]
We should not use owl-scroll as the divisions are not defined properly (i.e., the heights of different divs vary). The owl-scroll also hinders the user-experience. I will add smooth scroll which will fix the cross browser compatibility.
